# file: roles/elaticsearch/tasks/configure.yml

- name: Elasticsearch | Configure elasticsearch
  lineinfile: "{{ item }}"
  with_items:
    - dest=/etc/sysconfig/elasticsearch regexp='^.*ES_HEAP_SIZE=.*' line="ES_HEAP_SIZE=512m" state=present
    - dest=/etc/sysconfig/elasticsearch regexp='^.*ES_USER.*' line="ES_USER={{ elasticsearch_user }}" state=present
    - dest=/etc/elasticsearch/elasticsearch.yml regexp='^.*cluster.name:.*' line="cluster.name{{':'}} {{elasticsearch_cluster_name}}" state=present

- name: Elasticsearch | Start Elasticsearch
  service: name=elasticsearch state=restarted enabled=yes